# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Password < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/135yshr/password/releases/download/v0.1.2/password_Darwin_x86_64.tar.gz"
      sha256 "7cd0d13f26700905846ac78d221c2e82547924ea49f979efa9aa4841d72daff6"

      def install
        bin.install "mkpass"
      end
    end
    on_arm do
      url "https://github.com/135yshr/password/releases/download/v0.1.2/password_Darwin_arm64.tar.gz"
      sha256 "9c8471d004ec127b8dc5b0889213a6e2e75fe408ebbb73d6ef48b1b8246a4b78"

      def install
        bin.install "mkpass"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/135yshr/password/releases/download/v0.1.2/password_Linux_x86_64.tar.gz"
        sha256 "85fbae2dbd9473da67502469a20487f15427bb7248a4f7ffd1450333dd26cc70"

        def install
          bin.install "mkpass"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/135yshr/password/releases/download/v0.1.2/password_Linux_arm64.tar.gz"
        sha256 "eebe30c5b3916c779e0823d7c845e0d2e05f025959b1cdc9fcc13aca69315f62"

        def install
          bin.install "mkpass"
        end
      end
    end
  end
end
