# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Password < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Darwin_x86_64.tar.gz"
      sha256 "8a8ade00e3fac60417cbf03bc3b486289e5fb76e01a310c3f18a1437ba0fa629"

      def install
        bin.install "mkpass"
      end
    end
    on_arm do
      url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Darwin_arm64.tar.gz"
      sha256 "a1d100040758e64bdb177344b98ebc31f27bc98c0952c795853b6ce5936a4852"

      def install
        bin.install "mkpass"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Linux_x86_64.tar.gz"
        sha256 "9474b6cef62ff3035c2429948837d37452405411a19c4ed6e2fc642780149246"

        def install
          bin.install "mkpass"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Linux_arm64.tar.gz"
        sha256 "d86ca4810e61569e5cc6feae209cc136faa27128eccc079725b9ea513e40442f"

        def install
          bin.install "mkpass"
        end
      end
    end
  end
end
