# This file was generated by GoReleaser. DO NOT EDIT.
cask "meow" do
  version "0.22.0"

  on_macos do
    on_arm do
      sha256 "86d44b3c485e0bd5bcf3df08a208b8d2ab1698dd023a2cbd80bc7625d2616c91"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dfcd8d605b6d68f241a590b850caf7654b4540513d79a5d0002952c313acc8ce"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b052e28422213b6f33659fddb68cf4fa68e2c5366064534025e2f2dc0444e56f"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed37a3edee543eebff0c6d022b0ae06a25caeab210d3cfa19df3873935759a4a"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_linux_amd64.tar.gz"
    end
  end

  name "meow"
  desc "The purrfect functional programming language"
  homepage "https://github.com/135yshr/meow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meow"

  # No zap stanza required
end
