# This file was generated by GoReleaser. DO NOT EDIT.
cask "meow" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "898ac21004995f3bfebb162d33a859303f1ba837cd9ac18408fa04269fae1703"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
    on_arm do
      sha256 "3a48f09bfc6ec7c4cfcf6f662be40712f378184f8f1e57882d7cff04d6cad1d8"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e7841a5733668704d009f72becbc5fe354cccfb6e14fa62bd13875fb9763765"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_linux_amd64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
    on_arm do
      sha256 "36661f4d12a7d058be595b688335693a3ea6dcb63861921cb7732d1a05febd45"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_linux_arm64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
  end

  name "meow"
  desc "The purrfect functional programming language"
  homepage "https://github.com/135yshr/meow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meow"

  # No zap stanza required

end
