# This file was generated by GoReleaser. DO NOT EDIT.
cask "meow" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "16b2fa90602701f296e4727e8ddae3e8596d14757202f1fcae4bc16075f0eade"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
    on_arm do
      sha256 "ff43a25c82c3a06f924b6885e60abc8ae58518ad5d45396c726e805efa0c7cee"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
  end

  on_linux do
    on_intel do
      sha256 "7cab475a6d6cc54115212c9230a2dbb7bf7b14c53896adc520138c9aebb696fe"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_linux_amd64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
    on_arm do
      sha256 "ca65a7bf8a8bb69a904dfb7e653605eb01e84c763ff6b676952cd27e4a79d6aa"
      url "https://github.com/135yshr/meow/releases/download/v#{version}/meow_#{version}_linux_arm64.tar.gz",
        verified: "github.com/135yshr/meow"
    end
  end

  name "meow"
  desc "The purrfect functional programming language"
  homepage "https://github.com/135yshr/meow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meow"

  # No zap stanza required

end
