# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dvcx < Formula
  desc "Unofficial CLI for DevCycle Management API"
  homepage "https://github.com/135yshr/devcycle-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/135yshr/devcycle-cli/releases/download/v0.2.2/dvcx_0.2.2_darwin_amd64.tar.gz"
      sha256 "7cdb73e70307ee735a9778747e9abde1165918e40a3b23d175cdef768ab6d154"

      def install
        bin.install "dvcx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/135yshr/devcycle-cli/releases/download/v0.2.2/dvcx_0.2.2_darwin_arm64.tar.gz"
      sha256 "11d6ced7eed5602f2480ba02f310af028b0493884cb379bbdd5a8d9dcbb0c63f"

      def install
        bin.install "dvcx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/135yshr/devcycle-cli/releases/download/v0.2.2/dvcx_0.2.2_linux_amd64.tar.gz"
      sha256 "4d5ec7fb57e349f5682f2dc8bb386df9f7efe79c4d7bfd953ced04a5d4246023"
      def install
        bin.install "dvcx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/135yshr/devcycle-cli/releases/download/v0.2.2/dvcx_0.2.2_linux_arm64.tar.gz"
      sha256 "5b774a0d440774f1c1764c5bc09d4f45edd57a6b6bee003132fcad3b82bb5cb0"
      def install
        bin.install "dvcx"
      end
    end
  end

  test do
    system "#{bin}/dvcx", "version"
  end
end
