# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md2pdf < Formula
  desc "A CLI tool that converts Markdown files to PDF with GitHub-flavored styling"
  homepage "https://github.com/135yshr/md2pdf"
  version "0.19.0"
  license "MIT"

  depends_on "mermaid-cli"
  depends_on "pandoc" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/135yshr/md2pdf/releases/download/v0.19.0/md2pdf_0.19.0_darwin_amd64.tar.gz"
      sha256 "03a140661abc9347ac53376e228b585180453b370e2557c5ccd5aacf64b757d0"

      define_method(:install) do
        bin.install "md2pdf"
        bin.install_symlink bin/"md2pdf" => "mdview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/135yshr/md2pdf/releases/download/v0.19.0/md2pdf_0.19.0_darwin_arm64.tar.gz"
      sha256 "fa53bee2f41b566eef9452897f6e989fd448db2884b3034714157788dd82f3e2"

      define_method(:install) do
        bin.install "md2pdf"
        bin.install_symlink bin/"md2pdf" => "mdview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/135yshr/md2pdf/releases/download/v0.19.0/md2pdf_0.19.0_linux_amd64.tar.gz"
      sha256 "ede3381144cbfdcedaf5e1ab731ba32005c65a7ba9a4363bfeb28e0eb9457ba3"
      define_method(:install) do
        bin.install "md2pdf"
        bin.install_symlink bin/"md2pdf" => "mdview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/135yshr/md2pdf/releases/download/v0.19.0/md2pdf_0.19.0_linux_arm64.tar.gz"
      sha256 "81b8e43fd4d37569b8fa5fe37b975958a2e72bece2aec1f1effb709dc095dd92"
      define_method(:install) do
        bin.install "md2pdf"
        bin.install_symlink bin/"md2pdf" => "mdview"
      end
    end
  end

  test do
    assert_match "md2pdf version", shell_output("#{bin}/md2pdf -version")
    assert_match "mdview version", shell_output("#{bin}/mdview -version")
  end
end
