# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkpass < Formula
  desc ""
  homepage ""
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Darwin_x86_64.tar.gz"
      sha256 "d2614d0b37fea74f94d95c433b7635700875cf1846c612292b89077748f34ba8"

      def install
        bin.install "mkpass"
      end
    end
    on_arm do
      url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Darwin_arm64.tar.gz"
      sha256 "4f3a3b273975569ec6c115a921fb76af869d5de10d0fb1ac2af7aa6e90ca01a9"

      def install
        bin.install "mkpass"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Linux_x86_64.tar.gz"
        sha256 "d169a5bc7c08236e1512772ed3ee6c5c279f91d1db610bd92d30b5419d7dc7bb"

        def install
          bin.install "mkpass"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/135yshr/password/releases/download/v0.1.2/mkpass_Linux_arm64.tar.gz"
        sha256 "f9c5172adf5ae8dc942c0ac24695ebce77d864671f54fdfa8dc2f8dc2fef7ada"

        def install
          bin.install "mkpass"
        end
      end
    end
  end
end
